version: '3.8'

services:

  bookswap_db_postgres:
    image: postgres:16.0-alpine3.18
    container_name: bookswap_db_postgres
    environment:
      POSTGRES_USER: bookswap-api
      POSTGRES_PASSWORD: bookswapPassWord
      POSTGRES_DB: bookswap_db
    ports:
      - '5432:5432'