name: Java CI

on:
  push:
    branches:
      - dev
  workflow_dispatch:
  
permissions:
  contents: read
  checks: write
  id-token: write

jobs:

  tests:
    runs-on: ubuntu-latest

    steps:

      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up JDK
        uses: actions/setup-java@v4
        with:
          distribution: 'temurin'
          java-version: '21'
          cache: maven

      - name: Install dependencies
        run: ./mvnw install -DskipTests=true -Dmaven.javadoc.skip=true -B -V

      - name: Run tests and collect coverage
        run: ./mvnw -B test

      - name: Uploading Test results
        uses: actions/upload-artifact@v3.1.3
        with:
          name: test_results
          path: ./target/surefire-reports/TEST-*.xml

      - name: Uploading Coverage results
        uses: actions/upload-artifact@v3.1.3
        with:
          name: coverage_results
          path: ./target/site/jacoco/jacoco.xml

      - name: Tree
        run: tree -L 2

  build_report:

    runs-on: ubuntu-latest
    needs: [ tests ]
    permissions:
      contents: read
      packages: write
      id-token: write
    steps:
      - name: Loading Test results
        uses: actions/download-artifact@v3.0.2
        with:
          name: test_results

      - name: Publish Test Report
        uses: mikepenz/action-junit-report@v4
        if: success() || failure()
        with:
          report_paths: 'TEST-*.xml'

  upload_coverage:
    runs-on: ubuntu-latest
    needs: [ tests ]
    steps:
      - name: Loading Coverage results
        uses: actions/download-artifact@v3.0.2
        with:
          name: coverage_results

      - name: Upload coverage reports to Codecov
        uses: codecov/codecov-action@v3
        env:
          CODECOV_TOKEN: ${{ secrets.CODECOV_TOKEN }}

  update_main_branch:
    runs-on: ubuntu-latest
    needs: [ tests ]

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
        with:
          ref: main
          fetch-depth: 0

      - name: Merge dev into main
        run: |
          git config user.name "${{ github.actor }}"
          git config user.email "${{ github.actor }}@users.noreply.github.com"
          git merge dev --ff-only
          git push origin main
