name: Java CI

on:
  push:
    branches:
      - dev
  workflow_dispatch:

permissions:
  contents: write
  checks: write
  id-token: write

jobs:

  tests:
    runs-on: ubuntu-latest

    steps:

      - name: Checkout repository
        uses: actions/checkout@v4.1.1

      - name: Set up JDK
        uses: actions/setup-java@v4
        with:
          distribution: 'temurin'
          java-version: '21'
          cache: maven

      - name: Install dependencies
        run: ./mvnw install -DskipTests=true -Dmaven.javadoc.skip=true -B -V

      - name: Run tests and collect coverage
        run: ./mvnw -B test

      #      - name: Uploading Coverage results
      #        uses: actions/upload-artifact@v4.0.0
      #        with:
      #          name: coverage_results
      #          path: ./target/site/jacoco/jacoco.xml

      - name: Upload coverage reports to Codecov
        uses: codecov/codecov-action@v3.1.4
        env:
          CODECOV_TOKEN: ${{ secrets.CODECOV_TOKEN }}

      - name: Test Report
        uses: dorny/test-reporter@v1.7.0
        if: success() || failure()
        with:
          name: CBS Tests
          path: 'target/surefire-reports/TEST-*.xml'
          reporter: java-junit

      - name: Merge with main
        if: github.event_name == 'push' && success()
        run: |
          git fetch --all
          git config --local user.email "${{ github.actor }}@users.noreply.github.com"
          git config --local user.name "${{ github.actor }}"
          git checkout main
          git merge -Xtheirs --allow-unrelated-histories dev
          git push origin main

#  upload_coverage:
#    runs-on: ubuntu-latest
#    needs: [ tests ]
#    steps:
#      - name: Loading Coverage results
#        uses: actions/download-artifact@v4.1.0
#        with:
#          name: coverage_results

#      - name: Upload coverage reports to Codecov
#        uses: codecov/codecov-action@v3.1.4
#        env:
#          CODECOV_TOKEN: ${{ secrets.CODECOV_TOKEN }}